name: Manual Transfer Cron Job

on:
  workflow_dispatch

env:
  COUNTER_PLATFORM: ${{secrets.COUNTER_PLATFORM}}
  COUNTER_CARGOSEARCH: ${{secrets.COUNTER_CARGOSEARCH}}
  GOOGLE_SERVICE_ACCOUNT: ${{secrets.GOOGLE_SERVICE_ACCOUNT}}
  HIT_SHEET_URL_PLATFORM: ${{secrets.HIT_SHEET_URL_PLATFORM}}
  HIT_SHEET_URL_CARGOSEARCH: ${{secrets.HIT_SHEET_URL_CARGOSEARCH}}
  START_DATE: ${{secrets.START_DATE}}
  TOKEN: ${{secrets.TOKEN}}
  VISIT_SHEET_URL_PLATFORM: ${{secrets.VISIT_SHEET_URL_PLATFORM}}
  VISIT_SHEET_URL_CARGOSEARCH: ${{secrets.VISIT_SHEET_URL_CARGOSEARCH}}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Save Google creds
      run: |
        mkdir ~/.config/gspread
        echo "${{env.GOOGLE_SERVICE_ACCOUNT}}" > ~/.config/gspread/service_account.json

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.10.9

    - name: Install dependencies
      run: |
        python -m pip install -r requirements.txt
        echo "Dependency successfully installed"

    - name: Task
      run: |
        python main.py 
        echo "Success"
